### ISSUE TITLE
Error with sqlalchemy 2.0 version 

### ISSUE THREAD

**Issue by aghure** [codemation/pydbantic#55]
sqlalchemy.MetaData(self.engine) in giving error with sqlalchemy 2.0.
  
server.db = await Database.create(
  File "/python3.8/site-packages/pydbantic/database.py", line 655, in create
    new_db = cls(
  File "python3.8/site-packages/pydbantic/database.py", line 55, in __init__
    self.metadata = sqlalchemy.MetaData(self.engine)
   raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: expected schema argument to be a string, got <class 'sqlalchemy.engine.base.Engine'>.

**Comment by codemation** [comment]
@aghure pydbantic is only tested with sqlalchemy version 1.4.

**Comment by rmlopes** [comment]
At least with poetry it will be 1.4.28. It seems like metadata should be updated at least so that one can use the last 1.4.X version of sqlalchemy. Also I am integrating with FastAPI which is now using SQLAlchemy2. So it could save some time for newcomers to set it up properly so that at least the dependencies can be resolved automatically.

**Comment by codemation** [comment]
@rmlopes perhaps my message is not explicit enough, but yes indeed pydbantic is already tested along with `1.4.28` and would aim to support all `1.4.X` versions. Time constraints will likely delay supporting 2.0 for a bit.
